/** Centralized friendly microcopy for premium feel */

export const Copy = {
  /** Shared / cross-screen labels */
  common: {
    back: 'Back',
    next: 'Next',
    cancel: 'Cancel',
    close: 'Close',
    send: 'Send',
    save: 'Save',
    saving: 'Saving...',
    adding: 'Adding...',
    signIn: 'Sign in',
    signOut: 'Sign out',
    createDinner: 'Create Dinner',
    viewAllEvents: 'View all events',
    viewEvent: 'View event',
    addFromContacts: 'Add from contacts',
    loadingContacts: 'Loading contacts...',
    noContactsFound: 'No contacts with phone numbers or emails found.',
    addSelected: (count: number) => `Add selected (${count})`,
    location: 'Location',
    menu: 'Menu',
    bringList: 'Bring list',
    schedule: 'Schedule',
    rsvpBoard: 'RSVP board',
    navigate: 'Navigate',
    copyAddress: 'Copy address',
    addToCalendar: 'Add to calendar',
    shareLink: 'Share link',
    copyInviteLink: 'Copy invite link',
    optional: 'Optional',
    noData: 'Nothing here yet.',
    demoPreview: 'Demo Preview',
    dismiss: 'Dismiss',
  },
  /** Home / index tab */
  home: {
    heroTitle: 'Dinner Bell',
    heroSubtitle: 'Ring the bell and gather your people.',
    signInPrompt: 'Sign in to create events, RSVP, and get notified when it\'s time.',
    nextUp: 'Next Up',
    emptyHeadline: 'No dinners on the books yet.',
    emptyBody: 'Create a dinner, invite your people, and ring the bell when it\'s time.',
    emptyCta: 'Create your first Dinner Bell',
  },
  /** Events tab */
  events: {
    title: 'Events',
    subtitle: 'Your upcoming dinners, hangs, and little feasts.',
    noUpcoming: 'No upcoming dinners',
    noUpcomingBody: 'Create a dinner, invite your people, or see a demo to get started.',
    seeDemo: 'See a demo event',
    demoCreated: 'Demo event created! This is a local preview.',
    upcoming: 'Upcoming',
    past: 'Past',
    noPast: 'No past events yet. Your dinner memories will live here.',
    drafts: 'Drafts',
    noDrafts: 'Drafts are coming soon. Save events before you\'re ready to send.',
  },
  /** Profile tab */
  profile: {
    title: 'Profile',
    signInPrompt: 'Sign in to create and manage events',
    signInFullPrompt: 'Sign in to create and manage events, see your stats, and customize notifications.',
    hosted: 'Hosted',
    attended: 'Attended',
    claimed: 'Claimed',
    notifications: 'Notifications',
    defaultReminders: 'Default reminders',
    defaultRemindersDesc: 'Give people a gentle nudge before you ring.',
    bellSound: 'Bell sound',
    bellSoundDesc: 'Plays the triangle ding when it\'s time.',
    vibrateOnBell: 'Vibrate on bell',
    vibrateOnBellDesc: 'Feel it when the bell rings.',
    defaults: 'Defaults',
    defaultDuration: 'Default event duration',
    twoHours: '2 hours',
    bellFollowsStart: 'Bell follows start time',
    bellFollowsStartDesc: 'Ring right when the event begins.',
    defaultAddress: 'Default address',
    defaultAddressDesc: 'Manage your saved locations.',
    guestGroups: 'Guest groups',
    guestGroupsDesc: 'Reuse the same guest list for future events.',
    privacy: 'Privacy',
    showRsvp: 'Show my RSVP to others',
    showRsvpDesc: 'Let other guests see if you\'re going.',
    account: 'Account',
    phoneNumber: 'Phone number',
    phoneNumberDesc: 'So hosts can add you from their contacts and send you invite push notifications.',
    changeEmail: 'Change email',
    changeEmailDesc: 'Update your email address.',
    changePassword: 'Change password',
    changePasswordDesc: 'Update your password.',
    soon: 'Soon',
    sendReminders: 'Send me reminders',
  },
  /** Groups screens */
  groups: {
    signInPrompt: 'Sign in to manage guest groups.',
    newGroup: 'New group',
    creatingGroup: 'Creating...',
    createGroup: 'Create group',
    yourGroups: 'Your groups',
    noGroups: 'No groups yet. Create one to quickly invite the same people for future events.',
    deleteGroupTitle: 'Delete group',
    deleteGroupBody: 'Remove this group? Members are not removed from any events.',
    delete: 'Delete',
    addMember: 'Add member',
    contactType: 'Contact type',
    email: 'Email',
    phone: 'Phone',
    add: 'Add',
    members: (count: number) => `Members (${count})`,
    noMembers: 'No members yet.',
    remove: 'Remove',
  },
  /** Auth / sign-in */
  auth: {
    signInTitle: 'Sign in',
    signInPrompt: 'Enter your email and password.',
    createAccount: 'Create account',
    devSignIn: 'Dev sign in',
    emptyFields: 'Please enter your email and password to sign in.',
    invalidCredentials: 'Invalid email or password. Try again, or use Create account if you don\'t have one.',
    signUpEmptyFields: 'Enter an email and password (at least 6 characters).',
    passwordTooShort: 'Password must be at least 6 characters.',
    invalidEmailFormat: 'Please enter a valid email address.',
    signUpPrompt: 'Please enter your email and password (at least 6 characters) to create an account.',
    emailAlreadyRegistered: 'This email is already registered. Use Sign in instead.',
    signUpRejected: 'Sign-up was rejected. Check your email format and password, or try Sign in if you already have an account.',
    signInToCreate: 'Sign in to create an event',
    signInToCreateEvents: 'Sign in to create events',
  },
  /** Recap screen */
  recap: {
    thanks: 'Thanks for coming',
    whoCame: 'Who came',
    whatWasBrought: 'What was brought',
    doThisAgain: 'Host this again',
    backToEvent: 'Back to event',
    memoryCard: 'A great evening together.',
    noBringItems: 'No bring list items for this event.',
  },
  /** Event detail */
  event: {
    dinnerIsOn: 'Dinner is on',
    bellIn: (countdown: string) => `Bell in ${countdown}`,
    bellTimePassed: 'Bell time passed',
    hostedBy: (name: string) => `Hosted by ${name}`,
    tableAlmostReady: "Table's almost ready",
    bringListLookingGood: 'Bring list looking good',
    notFound: 'Event not found',
    notFoundBody: 'Check the link or try again later.',
    inviteLinkCopied: 'Invite link copied',
    cancelEvent: 'Cancel event',
    editEvent: 'Edit event',
    cancelled: 'This event has been cancelled',
    host: '(Host)',
    coHost: '(Co-host)',
    guest: '(Guest)',
    openChat: 'Open chat',
    inviteMore: 'Invite more',
    arrivalNotes: 'Arrival notes',
    imOnMyWay: "I'm ",
    minAway: ' min away',
    iveArrived: "I've arrived",
    addItem: '+ Add item',
    addSection: '+ Add section',
    addBringItem: '+ Add bring item',
    viewRecap: 'View recap',
    eventChat: 'Event chat',
    chatEmpty: 'No messages yet. Start the conversation!',
    guestEmail: 'Guest email',
    guestName: 'Name (optional)',
    enterEmail: 'Enter an email',
    addAndSendInvite: 'Add & send invite',
    orAddByPhone: 'Or add by phone',
    addByPhoneAndSend: 'Add by phone & send invite',
    shareLinkInstead: 'Share link instead',
    markProvided: 'Mark provided',
    going: 'Going',
    runningLate: 'Running late',
    maybe: 'Maybe',
    here: 'Here: ',
    onTheWay: 'On the way: ',
    ofClaimed: (claimed: number, total: number) => `${claimed} of ${total} claimed`,
    saveChanges: 'Save changes',
    demoCannotEdit: 'Demo events can\'t be edited.',
    onlyHostCanEdit: 'Only the host or co-hosts can edit this event.',
  },
  /** Invite screen */
  invite: {
    eventFull: 'This event is full',
    joinWaitlist: 'Join the waitlist',
    onWaitlist: "You're on the waitlist. We'll notify you if a spot opens up.",
    whatToExpect: 'What to expect',
    whoIsGoing: (count: number) => (count === 1 ? '1 person going' : `${count} people going`),
    shareCta: 'Share invite link',
    submitRsvp: 'Submit RSVP',
    viewEvent: 'View event',
    loadingInvite: 'Loading invite…',
    invalidInvite: 'This invite link may be invalid or expired.',
    checkLink: 'Check your link or ask the host for a new invite.',
    rsvpGoing: 'Going',
    rsvpLate: 'Running late',
    rsvpMaybe: 'Maybe',
    rsvpCant: "Can't make it",
    rsvp: 'RSVP',
    joining: 'Joining...',
  },
  /** Create event flow */
  create: {
    almostThere: 'Almost there!',
    createAndSend: 'Create & Send',
    creating: 'Creating...',
    stepBasics: 'Basics',
    stepLocation: 'Location',
    stepMenu: 'Menu',
    stepBringList: 'Bring List',
    stepSchedule: 'Schedule',
    stepHostTools: 'Host tools',
    stepInvite: 'Invite',
    stepReview: 'Review',
    publishSuccessHeadline: "You're all set!",
    publishSuccessBody: 'Your dinner is created. Invite your guests to get the party started.',
    inviteNowCta: 'Invite now',
    viewEventCta: 'View event',
    copyAddress: 'Copy address',
    startFromTemplate: 'Start from template',
    title: 'Title',
    startTime: 'Start time',
    pickStartTime: 'Pick start date & time',
    bellTime: 'Bell time',
    pickBellTime: 'Pick bell date & time',
    publicEvent: 'List in Discover (public event)',
    unitApt: 'Unit / Apt',
    locationNotes: 'Location notes (parking, gate code)',
    quickAdd: 'Quick add',
    category: 'Category',
    claimable: 'Claimable',
    required: 'Required',
    noteToGuests: 'Note to guests (optional)',
    inviteGroup: 'Invite a group',
    guestsPlaceholder: 'Guests (email or phone, one per line or comma-separated)',
    shareInviteAfter: 'Or share the invite link after creating the event.',
    bellLabel: 'Bell: ',
    menuSectionsLabel: 'Menu sections: ',
    bringItemsLabel: 'Bring items: ',
  },
  /** Validation / errors */
  validation: {
    required: (field: string) => `${field} is required`,
    invalidEmail: 'Please enter a valid email address',
    invalidPhone: 'Please enter a valid phone number',
    genericError: 'Something went wrong. Please try again.',
    networkError: 'Check your connection and try again.',
    duplicateGuest: 'This person has already been invited.',
    expiredInvite: 'This invite has expired or is no longer valid.',
    inviteDeliveryFailed: (count: number) =>
      `Invite added, but ${count === 1 ? 'delivery failed once' : `${count} deliveries failed`}. You can copy the invite link and send it manually.`,
  },
  /** Bring list */
  bringList: {
    claimed: 'Claimed',
    unclaimed: 'Unclaimed',
    provided: 'Provided',
    needed: 'Needed',
    optional: 'Optional',
    illBringThis: "I'll bring this",
    claiming: 'Claiming...',
    alreadyClaimed: 'Already claimed by someone else',
    quantityLabel: "Quantity you'll bring",
    messageLabel: 'Optional message (e.g. "I can bring extra cups too")',
  },
  /** Toast messages */
  toast: {
    bringListComplete: 'Bring list complete!',
    youreHere: "You're here! Host has been notified.",
    addedToCalendar: 'Added to your calendar.',
    calendarFailed: 'Could not add to calendar.',
    signedOut: 'Signed out. Come back hungry.',
    invalidPhone: 'Enter a valid phone number (at least 10 digits).',
    phoneSaveFailed: 'Could not save phone number.',
    phoneSaved: 'Phone number saved. Hosts can invite you by this number.',
    phoneCleared: 'Phone number cleared.',
    guestsAdded: (count: number) => `Added ${count} guest${count > 1 ? 's' : ''}; email/text was sent when available (plus push for app users).`,
    noGuestsAdded: 'No guests added.',
    guestAdded: 'Guest added; email/text sent when available, plus push if they have the app.',
    demoCreated: 'Demo event created! This is a local preview.',
    linkInvalid: 'Something went wrong with that link.',
  },
  /** Placeholders */
  placeholder: {
    email: 'email@example.com',
    password: 'Password',
    yourName: 'Your name',
    phoneOrEmail: 'Phone or email',
    guestName: 'Guest name',
    phoneNumber: 'Phone number',
    phoneExample: '+1 234 567 8900',
    itemName: 'Item name',
    quantity: 'Qty',
    streetAddress: 'Street address',
    city: 'City',
    state: 'State',
    postalCode: 'Postal code',
    country: 'Country',
    dateTimePlaceholder: 'YYYY-MM-DDTHH:mm',
    eventTitle: "e.g. Thursday Dinner at Caleb's",
    sectionTitle: 'e.g. Main, Dessert',
    menuItemName: 'Item name',
    locationNotes: 'Optional',
    noteToGuests: "e.g. Can't wait to see you! Bring your appetite.",
    guestsInput: 'email@example.com or 5551234567',
    groupName: 'Group name (e.g. Family)',
    memberName: 'Name',
    contactEmail: 'email@example.com',
    contactPhone: '5551234567',
    capacityExample: 'e.g. 12',
    sectionExample: 'e.g. Main',
    prepTask: 'e.g. Preheat oven',
    coHostEmail: 'Co-host email',
    scheduleTitle: 'Title',
    scheduleTime: 'Time (optional)',
    chatMessage: 'Message...',
    bringQuantity: 'e.g. 2 bottles',
  },
  /** Deep link handler */
  deepLink: {
    invalidInvite: 'This invite link may be invalid or expired.',
    linkError: 'Something went wrong with that link.',
  },
  /** Not found screen */
  notFound: {
    title: "This screen doesn't exist.",
    goHome: 'Go to home screen!',
  },
  /** Offline / network */
  offline: {
    banner: "You're offline. Some features may not work.",
    retry: 'Retry',
  },
} as const;
